# Site settings
title: Eric Prunier
email:
description: > # this means to ignore newlines until "baseurl:"
  Bloc note et analyses techniques.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ericprunier.com" # the base hostname & protocol for your site
twitter_username: EricPrunier
github_username: eprunier
paginate: 5
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
